### ISSUE TITLE
HPSF: Data License Change

### ISSUE THREAD

**Issue by ax3l** [BLAST-WarpX/warpx-data#4]
As part of joining the [HPSF](https://hpsf.io/), we might want to unify the licensing here.

In our draft technical charter, we write that we would license data under CDLA-Permissive 2.0 License, available at https://cdla.dev/permissive-2-0.

**Comment by ax3l** [comment]
@roelof-groenewald can you coordinate this effort?

I would suggest to add a README and LICENSE file and gathering approval by prior commiters of this repo in the PR that adds it.

**Comment by roelof-groenewald** [comment]
Sure thing. I'll get this started tomorrow.
